INCLUDE ../globals.ink

{A_ACTOR}: Ahhhhhh! Eu não estou conseguindo dormir!
{A_ACTOR}: Se eu fizer a prova com sono, com certeza acabarei indo mal.
{A_ACTOR}: Talvez eu devesse só não ir amanhã de novo...
{A_ACTOR}: Não! Eu não posso fazer isso!
{A_ACTOR}: Não depois de todo o trabalho que o {format_name(player_name)} teve para me ajudar...
{A_ACTOR}: E ele vai vir aqui amanhã para irmos juntos.
{A_ACTOR}: Eu preciso tentar me acalmar...